#!/bin/bash

wallpaper=`ls -1 ./wallpapers | rofi -dmenu` 

while getopts ld option
do
  case "${option}"
    in

    l) 
      wal -l -i ./wallpapers/$wallpaper;;
    
    d)
      wal -i  ./wallpapers/$wallpaper ;;
    
esac
done

pywalfox update
pywal-discord 
cp -v /home/andrija/.cache/wal/colors.css /home/andrija/configs/startpage_extension/src/colors.css



